# Generated by Django 5.0.4 on 2024-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritelocation',
            name='name',
            field=models.CharField(default='Old favourite', max_length=50),
        ),
    ]
