# Generated by Django 5.0.4 on 2024-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatheruser',
            name='paying',
            field=models.BooleanField(default=False),
        ),
    ]
