name: Django CI

on:
  push:
    branches:
      - 'feature/**'
      - 'master'
      - 'dev'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run -m pytest
      env:
        CURRENT_WEATHER_API_URL: ${{ vars.CURRENT_WEATHER_API_URL }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GEOCODING_API_URL: ${{ vars.GEOCODING_API_URL }}
    - name: Coverage
      run: |
        coverage report -m
      env:
        CURRENT_WEATHER_API_URL: ${{ vars.CURRENT_WEATHER_API_URL }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GEOCODING_API_URL: ${{ vars.GEOCODING_API_URL }}
