name: Django CI

on:
  push:
    branches:
      - 'feature/**'
      - 'master'
      - 'dev'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    env:
      CURRENT_WEATHER_API_URL: ${{ vars.CURRENT_WEATHER_API_URL }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEFAULT_CITY: ${{ vars.DEFAULT_CITY }}
      FORECAST_API_URL: ${{ vars.FORECAST_API_URL }}
      HISTORY_API_URL: ${{ vars.HISTORY_API_URL }}
      USER_API_KEY: ${{ vars.USER_API_KEY }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_SSLMODE: ${{ vars.DB_SSLMODE }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run PostgreSQL Service
      run: |
        sudo systemctl enable postgresql
        sudo systemctl start postgresql
    - name: Check PostgreSQL Service
      run: |
        sudo systemctl status postgresql
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Collect static files
      run: |
        python manage.py collectstatic --no-input
    - name: Run Tests
      env:
        CURRENT_WEATHER_API_URL: ${{ vars.CURRENT_WEATHER_API_URL }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEFAULT_CITY: ${{ vars.DEFAULT_CITY }}
        FORECAST_API_URL: ${{ vars.FORECAST_API_URL }}
        HISTORY_API_URL: ${{ vars.HISTORY_API_URL }}
        USER_API_KEY: ${{ vars.USER_API_KEY }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USER: ${{ vars.DB_USER }}
        DB_PASSWORD: ${{ vars.DB_PASSWORD }}
        DB_HOST: ${{ vars.DB_HOST }}
        DB_PORT: ${{ vars.DB_PORT }}
        DB_SSLMODE: ${{ vars.DB_SSLMODE }}
      run: |
        coverage run -m pytest

    - name: Coverage
      run: |
        coverage report -m
